cmd:
  - "kill"
  - "status"



# Be sure to follow the pattern of the config or else you will get errors!
# My GitHub for more amazing plugins/creations like these!: MXGLatoya
# Discord Server: https://discord.gg/Gfm4ZZE
# Plugin Developed by MXGLatoya
